### PR TITLE
googlechrome: Fix autoupdate

### PR DESCRIPTION
**Pull request by alexchapar**
## What type of Apps related PR is this? (check all applicable)

- [ ] ✨ Add Manifest
- [x] ♻️ Refactor
- [x] 🐛 Bug Fix
- [ ] 👷 Optimization
- [ ] 🚩 Other

## Description

Fix the autoupdate for Google Chrome, which was no longer working from the previous uri. A new one has been publish with ScoopInstaller.

## Related Tickets & Documents

None

### Add/Modify a description in the manifest?

- [x] 👍 yes
- [ ] 🙋 yes, but I need help
- [ ] 🙅 no, because they aren't needed

### Check URLs?

- [x] 👍 yes
- [ ] 🙋 yes, but I need help
- [ ] 🙅 no, because they aren't needed

### Update to the latest version?

- [x] 👍 yes
- [ ] 🙋 yes, but I need help
- [ ] 🙅 no, because they aren't needed

### Update Hashes?

- [x] 👍 yes
- [ ] 🙋 yes, but I need help
- [ ] 🙅 no, because they aren't needed

### Format the json manifest?

- [x] 👍 yes
- [ ] 🙋 yes, but I need help
- [ ] 🙅 no, because they aren't needed

### Notes in the manifest?

- [ ] 👍 yes
- [ ] 🙋 yes, but I need help
- [x] 🙅 no, because they aren't needed

### Application Dependencies?

- [ ] 👍 yes
- [ ] 🙋 yes, but I need help
- [x] 🙅 no, because they aren't needed

### Application Suggestions?

- [ ] 👍 yes
- [ ] 🙋 yes, but I need help
- [x] 🙅 no, because they aren't needed

### Pre-installation steps to perform?

- [ ] 👍 yes
- [ ] 🙋 yes, but I need help
- [x] 🙅 no, because they aren't needed

### Post-installation steps to perform?

- [ ] 👍 yes
- [ ] 🙋 yes, but I need help
- [x] 🙅 no, because they aren't needed

### File persistence to perform?

- [ ] 👍 yes
- [ ] 🙋 yes, but I need help
- [x] 🙅 no, because they aren't needed

## [optional] What gif/emoji best describes this PR or how it makes you feel?

:alien: :bug: :bricks:

### CODE REVIEW

**Comment by BotServiceAutomation** [comment]
All changes look good.

Wait for review from human collaborators.
### googlechrome

- [x] Description
- [x] License
- [x] Hashes
- [x] Checkver
- [x] Autoupdate
- [x] Autoupdate Hash Extraction

**Review by GProulx — COMMENTED** [review]
As Scoop "Extras" bucket already defines googlechrome, should we use that one instead of duplicate it? Or it's with the objective of using only "our" bucket in the future?

https://github.com/ScoopInstaller/Extras/blob/master/bucket/googlechrome.json

**Comment by Bibz87-CG** [comment]
> As Scoop "Extras" bucket already defines googlechrome, should we use that one instead of duplicate it? Or it's with the objective of using only "our" bucket in the future?
> 
> https://github.com/ScoopInstaller/Extras/blob/master/bucket/googlechrome.json

Since our "business" bucket has a name that is alphabetically before the "Extras" bucket, its manifests are used first, making it possible to "override" app versions that aren't the same as "Extras"'s. This would be useful in case there's a version with critical bugs or security issues.

**Comment by alexchapar** [comment]
Also, the idea behind "scoop-the-business" was to demonstrate it was possible to be "owner" of the apps that we want to include and how we want to install them (aka.: like it was managed in a business perspective). This is a good exemple here, since the googlechrome from extras force a userdata in the persistent files of scoop (which could be a good idea by the way). But here I didn't implement it to use the chrome default behavior. 

Also like @Bibz87-CG mentioned our bucket come first ;), so it will install our "version" before other (unless we specify the bucket to use when installing an app)

**Review by GProulx — APPROVED** [review]

**Pull request merged**
