### PR TITLE
edgedriver: Update to version 108.0.1462.20 and fix checkver

### PR DESCRIPTION
**Pull request by alexchapar**
## What type of Apps related PR is this? (check all applicable)
- [ ] ✨ Add Manifest
- [ ] ♻️ Refactor
- [x] 🐛 Bug Fix
- [ ] 👷 Optimization
- [x] 🚩 Other

## Description
Update the edgedriver to the newest version, add arm64 support. Also, the response from the edgedriver LATEST_BETA is now in unicode, so we need to change how checkver is obtained

## Related Tickets & Documents
None, except the excavator wasn't able to obtain the new version

## [optional] What gif/emoji best describes this PR or how it makes you feel?
:alien: :bug: :package:

### Add/Modify a description in the manifest?
- [x] 👍 yes
- [ ] 🙋 yes, but I need help
- [ ] 🙅 no, because they aren't needed

### Check URLs?
- [x] 👍 yes
- [ ] 🙋 yes, but I need help
- [ ] 🙅 no, because they aren't needed

### Update to the latest version?
- [x] 👍 yes
- [ ] 🙋 yes, but I need help
- [ ] 🙅 no, because they aren't needed

### Update Hashes?
- [x] 👍 yes
- [ ] 🙋 yes, but I need help
- [ ] 🙅 no, because they aren't needed

### Format the json manifest?
- [x] 👍 yes
- [ ] 🙋 yes, but I need help
- [ ] 🙅 no, because they aren't needed

### Notes in the manifest?
- [x] 👍 yes
- [ ] 🙋 yes, but I need help
- [ ] 🙅 no, because they aren't needed

### Application Dependencies?
- [ ] 👍 yes
- [ ] 🙋 yes, but I need help
- [x] 🙅 no, because they aren't needed

### Application Suggestions?
- [ ] 👍 yes
- [ ] 🙋 yes, but I need help
- [x] 🙅 no, because they aren't needed

### Pre-installation steps to perform?
- [ ] 👍 yes
- [ ] 🙋 yes, but I need help
- [x] 🙅 no, because they aren't needed

### Post-installation steps to perform?
- [ ] 👍 yes
- [ ] 🙋 yes, but I need help
- [x] 🙅 no, because they aren't needed

### File persistence to perform?
- [ ] 👍 yes
- [ ] 🙋 yes, but I need help
- [x] 🙅 no, because they aren't needed

### CODE REVIEW

**Comment by BotServiceAutomation** [comment]
[Your changes do not pass checks.](https://github.com/Ash258/Scoop-GithubActions/wiki/Pull-Request-Checks)
### edgedriver

- [x] Description
- [x] License
- [x] Hashes
- [ ] Checkver
- [x] Autoupdate

**Comment by BotServiceAutomation** [comment]
All changes look good.

Wait for review from human collaborators.
### edgedriver

- [x] Description
- [x] License
- [x] Hashes
- [x] Checkver
- [x] Autoupdate

**Comment by BotServiceAutomation** [comment]
All changes look good.

Wait for review from human collaborators.
### edgedriver

- [x] Description
- [x] License
- [x] Hashes
- [x] Checkver
- [x] Autoupdate

**Comment by BotServiceAutomation** [comment]
All changes look good.

Wait for review from human collaborators.
### edgedriver

- [x] Description
- [x] License
- [x] Hashes
- [x] Checkver
- [x] Autoupdate

**Comment by BotServiceAutomation** [comment]
All changes look good.

Wait for review from human collaborators.
### edgedriver

- [x] Description
- [x] License
- [x] Hashes
- [x] Checkver
- [x] Autoupdate

**Comment by BotServiceAutomation** [comment]
All changes look good.

Wait for review from human collaborators.
### edgedriver

- [x] Description
- [x] License
- [x] Hashes
- [x] Checkver
- [x] Autoupdate

**Review by alexchapar — COMMENTED** [review]
/verify

**Comment by BotServiceAutomation** [comment]
All changes look good.

Wait for review from human collaborators.
### edgedriver

- [x] Description
- [x] License
- [x] Hashes
- [x] Checkver
- [x] Autoupdate

**Review by Bibz87 — APPROVED** [review]

**Pull request merged**
