### PR TITLE
Fix inkscape manifest

### PR DESCRIPTION
**Pull request by Bibz87**
## What type of Apps related PR is this? (check all applicable)

- [ ] ✨ Add Manifest
- [ ] ♻️ Refactor
- [X] 🐛 Bug Fix
- [ ] 👷 Optimization
- [ ] 🚩 Other

## Description
Inkscape seems to have changed how it distributes new versions. Extras' manifest has been recovered to fix the business bucket. 

## Related Tickets & Documents
#92 

## [optional] What gif/emoji best describes this PR or how it makes you feel?
🐛💚

### Add/Modify a description in the manifest?

- [x] 👍 yes
- [ ] 🙋 yes, but I need help
- [ ] 🙅 no, because they aren't needed

### Check URLs?

- [x] 👍 yes
- [ ] 🙋 yes, but I need help
- [ ] 🙅 no, because they aren't needed

### Update to the latest version?

- [x] 👍 yes
- [ ] 🙋 yes, but I need help
- [ ] 🙅 no, because they aren't needed

### Update Hashes?

- [x] 👍 yes
- [ ] 🙋 yes, but I need help
- [ ] 🙅 no, because they aren't needed

### Format the json manifest?

- [x] 👍 yes
- [ ] 🙋 yes, but I need help
- [ ] 🙅 no, because they aren't needed

### Notes in the manifest?

- [ ] 👍 yes
- [ ] 🙋 yes, but I need help
- [x] 🙅 no, because they aren't needed

### Application Dependencies?

- [ ] 👍 yes
- [ ] 🙋 yes, but I need help
- [x] 🙅 no, because they aren't needed

### Application Suggestions?

- [ ] 👍 yes
- [ ] 🙋 yes, but I need help
- [x] 🙅 no, because they aren't needed

### Pre-installation steps to perform?

- [ ] 👍 yes
- [ ] 🙋 yes, but I need help
- [x] 🙅 no, because they aren't needed

### Post-installation steps to perform?

- [ ] 👍 yes
- [ ] 🙋 yes, but I need help
- [x] 🙅 no, because they aren't needed

### File persistence to perform?

- [ ] 👍 yes
- [ ] 🙋 yes, but I need help
- [x] 🙅 no, because they aren't needed

### CODE REVIEW

**Comment by Bibz87** [comment]
Inkscape fails in Extras' excavator, too. 😒

**Comment by alexchapar** [comment]
> Inkscape fails in Extras' excavator, too. 😒

you can file a bug 😉

**Comment by alexchapar** [comment]
there already a bug 😉 : #92

**Comment by Bibz87** [comment]
> there is already a bug 😉 : #92

I know, it's in the _Related Tickets & Documents_ section of the PR :)

**Comment by alexchapar** [comment]
> > there is already a bug 😉 : #92
> 
> I know, it's in the _Related Tickets & Documents_ section of the PR :)

You could reopen the PR... I kinda found the issue... (it is a little bit weird/tricky...)

It seems that the, I assume, "commitshash" used at the end of the filename differs between x64 and x86... Buuuut it is true for the current "new" 1.3.2 version and it was not the case for the 1.3.1... ＼_(O_o)_／

So we could decide to either rip off x86, or do some little scripting (aka copy/paste-ish) to have a cleanfilename_x64 and cleanfilename_x86... 

Also, I would personally prefer to have the "version" to fit with the semver instead of having the date and hash...

**Comment by Bibz87** [comment]
> > > there is already a bug 😉 : #92
> > 
> > 
> > I know, it's in the _Related Tickets & Documents_ section of the PR :)
> 
> You could reopen the PR... I kinda found the issue... (it is a little bit weird/tricky...)
> 
> It seems that the, I assume, "commithash" used at the end of the filename differs between x64 and x86... Buuuut it is true for the current "new" 1.3.2 version and it was not the case for the 1.3.1... ＼_(O_o)_／
> 
> So we could decide to either rip off x86, or do some little scripting (aka copy/paste-ish) to have a cleanfilename_x64 and cleanfilename_x86...
> 
> Also, I would personally prefer to have the "version" to fit with the semver instead of having the date and hash...

Alright, I'll rip out x86, like I did for GitKraken.

**Comment by BotServiceAutomation** [comment]
[Your changes do not pass checks.](https://github.com/ScoopInstaller/GithubActions/wiki/Pull-Request-Checks)
### inkscape

- [x] Description
- [x] License
- [x] Hashes
- [ ] Checkver
- [ ] Autoupdate
- [ ] Autoupdate Hash Extraction

**Comment by BotServiceAutomation** [comment]
[Your changes do not pass checks.](https://github.com/ScoopInstaller/GithubActions/wiki/Pull-Request-Checks)
### inkscape

- [x] Description
- [x] License
- [x] Hashes
- [ ] Checkver
- [x] Autoupdate
- [x] Autoupdate Hash Extraction

**Comment by BotServiceAutomation** [comment]
[Your changes do not pass checks.](https://github.com/ScoopInstaller/GithubActions/wiki/Pull-Request-Checks)
### inkscape

- [x] Description
- [x] License
- [ ] Hashes
- [x] Checkver
- [x] Autoupdate
- [x] Autoupdate Hash Extraction

**Comment by BotServiceAutomation** [comment]
All changes look good.

Wait for review from human collaborators.
### inkscape

- [x] Description
- [x] License
- [x] Hashes
- [x] Checkver
- [x] Autoupdate
- [x] Autoupdate Hash Extraction

**Comment by BotServiceAutomation** [comment]
All changes look good.

Wait for review from human collaborators.
### inkscape

- [x] Description
- [x] License
- [x] Hashes
- [x] Checkver
- [x] Autoupdate
- [x] Autoupdate Hash Extraction

**Review by alexchapar — APPROVED** [review]

**Pull request merged**
