### PR TITLE
winget-cli: Update to version 1.3.2691

### PR DESCRIPTION
**Pull request by alexchapar**
## What type of Apps related PR is this? (check all applicable)
- [ ] ✨ Add Manifest
- [ ] ♻️ Refactor
- [x] 🐛 Bug Fix
- [ ] 👷 Optimization
- [x] 🚩 Other

## Description
The winget releases did change awhile ago, but we didn't see/know that... 

## Related Tickets & Documents
#67  ( well it seems that the Excavator knew it but didn't announce it :confounded: )

## [optional] What gif/emoji best describes this PR or how it makes you feel?
:fire: :alien: :clown_face:

### Add/Modify a description in the manifest?
- [x] 👍 yes
- [ ] 🙋 yes, but I need help
- [ ] 🙅 no, because they aren't needed

### Check URLs?
- [x] 👍 yes
- [ ] 🙋 yes, but I need help
- [ ] 🙅 no, because they aren't needed

### Update to the latest version?
- [x] 👍 yes
- [ ] 🙋 yes, but I need help
- [ ] 🙅 no, because they aren't needed

### Update Hashes?
- [x] 👍 yes
- [ ] 🙋 yes, but I need help
- [ ] 🙅 no, because they aren't needed

### Format the json manifest?
- [x] 👍 yes
- [ ] 🙋 yes, but I need help
- [ ] 🙅 no, because they aren't needed

### Notes in the manifest?
- [x] 👍 yes
- [ ] 🙋 yes, but I need help
- [ ] 🙅 no, because they aren't needed

### Application Dependencies?
- [ ] 👍 yes
- [ ] 🙋 yes, but I need help
- [x] 🙅 no, because they aren't needed

### Application Suggestions?
- [x] 👍 yes
- [ ] 🙋 yes, but I need help
- [ ] 🙅 no, because they aren't needed

### Pre-installation steps to perform?
- [ ] 👍 yes
- [ ] 🙋 yes, but I need help
- [x] 🙅 no, because they aren't needed

### Post-installation steps to perform?
- [ ] 👍 yes
- [ ] 🙋 yes, but I need help
- [x] 🙅 no, because they aren't needed

### File persistence to perform?
- [ ] 👍 yes
- [ ] 🙋 yes, but I need help
- [x] 🙅 no, because they aren't needed

### CODE REVIEW

**Comment by BotServiceAutomation** [comment]
All changes look good.

Wait for review from human collaborators.
### winget-cli

- [x] Description
- [x] License
- [x] Hashes
- [x] Checkver
- [x] Autoupdate
- [x] Autoupdate Hash Extraction

**Comment by alexchapar** [comment]
We should rename it to fit with the "main" bucket

**Review by Bibz87 — APPROVED** [review]

**Review by alexchapar — COMMENTED** [review]
keep the old name with as obsolete... and add this one as winget.json this way we will be "inline" with the main bucket

**Comment by alexchapar** [comment]
> keep the old name with as obsolete... and add this one as winget.json this way we will be "inline" with the main bucket

Unfortunately, the old version is no longer supporter nor available : https://github.com/microsoft/winget-cli/releases/v1.0.11451 :no_good::trollface:

**Comment by alexchapar** [comment]
\verify

**Comment by BotServiceAutomation** [comment]
All changes look good.

Wait for review from human collaborators.
### winget

- [x] Description
- [x] License
- [x] Hashes
- [x] Checkver
- [x] Autoupdate
- [x] Autoupdate Hash Extraction

**Pull request merged**
